### ISSUE TITLE
README License copyright is it right?

### ISSUE THREAD

**Issue by ifraixedes** [tweeio/twee-framework#2]
After I've taken a look to the contributors, I'm not really sure if the copyright notice in the README's license section is right.

**Comment by sbrsv** [comment]
What do you mean? 
MIT license is not correctly formulated?

**Comment by ifraixedes** [comment]
You've updated it, I was referring to https://github.com/tweeio/twee-framework/commit/fd41cb69003f31f40bf43ed93c3fd0c96d2bf29e#diff-04c6e90faac2675aa89e2176d2eec7d8L108
